version: '3.9'

services:
  # Define the PostgreSQL service
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stagedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Define the Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stagedb
    ports:
      - "8080:8080"
    depends_on:
      - db

# Define a named volume for PostgreSQL data persistence
volumes:
  pgdata:
